# Generated by Django 1.10.4 on 2018-03-02 05:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='feed',
        ),
        migrations.AddField(
            model_name='notification',
            name='package_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
