# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-02 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20180302_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('F', 'Favorite'), ('L', 'Like')], max_length=1),
        ),
    ]
