msgid "Afghanistan"
msgstr "アフガニスタン"

msgid "Albania"
msgstr "アルバニア"

msgid "Algeria"
msgstr "アルジェリア"

msgid "American Samoa"
msgstr "アメリカ領サモア"

msgid "Andorra"
msgstr "アンドラ"

msgid "Angola"
msgstr "アンゴラ"

msgid "Anguilla"
msgstr "アンギラ"

msgid "Antarctica"
msgstr "南極"

msgid "Antigua and Barbuda"
msgstr "アンティグア・バーブーダ"

msgid "Argentina"
msgstr "アルゼンチン"

msgid "Armenia"
msgstr "アルメニア"

msgid "Aruba"
msgstr "アルバ"

msgid "Australia"
msgstr "オーストラリア"

msgid "Austria"
msgstr "オーストリア"

msgid "Azerbaijan"
msgstr "アゼルバイジャン"

msgid "Bahamas"
msgstr "バハマ"

msgid "Bahrain"
msgstr "バーレーン"

msgid "Bangladesh"
msgstr "バングラデシュ"

msgid "Barbados"
msgstr "バルバドス"

msgid "Belarus"
msgstr "ベラルーシ"

msgid "Belgium"
msgstr "ベルギー"

msgid "Belize"
msgstr "ベリーズ"

msgid "Benin"
msgstr "ベナン"

msgid "Bermuda"
msgstr "バミューダ"

msgid "Bhutan"
msgstr "ブータン"

msgid ""Bolivia"
msgstr "ボリビア多民族国"

msgid ""Bonaire"
msgstr "ボネール、シント・ユースタティウスおよびサバ"

msgid "Bosnia and Herzegovina"
msgstr "ボスニア・ヘルツェゴビナ"

msgid "Botswana"
msgstr "ボツワナ"

msgid "Bouvet Island"
msgstr "ブーベ島"

msgid "Brazil"
msgstr "ブラジル"

msgid "British Indian Ocean Territory"
msgstr "イギリス領インド洋地域"

msgid "Brunei Darussalam"
msgstr "ブルネイ・ダルサラーム"

msgid "Bulgaria"
msgstr "ブルガリア"

msgid "Burkina Faso"
msgstr "ブルキナファソ"

msgid "Burundi"
msgstr "ブルンジ"

msgid "Cambodia"
msgstr "カンボジア"

msgid "Cameroon"
msgstr "カメルーン"

msgid "Canada"
msgstr "カナダ"

msgid "Cape Verde"
msgstr "カーボベルデ"

msgid "Cayman Islands"
msgstr "ケイマン諸島"

msgid "Central African Republic"
msgstr "中央アフリカ共和国"

msgid "Chad"
msgstr "チャド"

msgid "Chile"
msgstr "チリ"

msgid "China"
msgstr "中華人民共和国"

msgid "Christmas Island"
msgstr "クリスマス島"

msgid "Cocos (Keeling) Islands"
msgstr "ココス（キーリング）諸島"

msgid "Colombia"
msgstr "コロンビア"

msgid "Comoros"
msgstr "コモロ"

msgid "Congo"
msgstr "コンゴ共和国"

msgid ""Congo"
msgstr "コンゴ民主共和国"

msgid "Cook Islands"
msgstr "クック諸島"

msgid "Costa Rica"
msgstr "コスタリカ"

msgid "Croatia"
msgstr "クロアチア"

msgid "Cuba"
msgstr "キューバ"

msgid "Cura?ao"
msgstr "キュラソー"

msgid "Cyprus"
msgstr "キプロス"

msgid "Czechia"
msgstr "チェコ"

msgid "C?te d'Ivoire"
msgstr "コートジボワール"

msgid "Denmark"
msgstr "デンマーク"

msgid "Djibouti"
msgstr "ジブチ"

msgid "Dominica"
msgstr "ドミニカ国"

msgid "Dominican Republic"
msgstr "ドミニカ共和国"

msgid "Ecuador"
msgstr "エクアドル"

msgid "Egypt"
msgstr "エジプト"

msgid "El Salvador"
msgstr "エルサルバドル"

msgid "Equatorial Guinea"
msgstr "赤道ギニア"

msgid "Eritrea"
msgstr "エリトリア"

msgid "Estonia"
msgstr "エストニア"

msgid "Ethiopia"
msgstr "エチオピア"

msgid "Falkland Islands (Malvinas)"
msgstr "フォークランド（マルビナス）諸島"

msgid "Faroe Islands"
msgstr "フェロー諸島"

msgid "Fiji"
msgstr "フィジー"

msgid "Finland"
msgstr "フィンランド"

msgid "France"
msgstr "フランス"

msgid "French Guiana"
msgstr "フランス領ギアナ"

msgid "French Polynesia"
msgstr "フランス領ポリネシア"

msgid "French Southern Territories"
msgstr "フランス領南方・南極地域"

msgid "Gabon"
msgstr "ガボン"

msgid "Gambia"
msgstr "ガンビア"

msgid "Georgia"
msgstr "ジョージア"

msgid "Germany"
msgstr "ドイツ"

msgid "Ghana"
msgstr "ガーナ"

msgid "Gibraltar"
msgstr "ジブラルタル"

msgid "Greece"
msgstr "ギリシャ"

msgid "Greenland"
msgstr "グリーンランド"

msgid "Grenada"
msgstr "グレナダ"

msgid "Guadeloupe"
msgstr "グアドループ"

msgid "Guam"
msgstr "グアム"

msgid "Guatemala"
msgstr "グアテマラ"

msgid "Guernsey"
msgstr "ガーンジー"

msgid "Guinea"
msgstr "ギニア"

msgid "Guinea-Bissau"
msgstr "ギニアビサウ"

msgid "Guyana"
msgstr "ガイアナ"

msgid "Haiti"
msgstr "ハイチ"

msgid "Heard Island and McDonald Islands"
msgstr "ハード島とマクドナルド諸島"

msgid "Holy See (Vatican City State)"
msgstr "バチカン市国"

msgid "Honduras"
msgstr "ホンジュラス"

msgid "Hong Kong"
msgstr "香港"

msgid "Hungary"
msgstr "ハンガリー"

msgid "Iceland"
msgstr "アイスランド"

msgid "India"
msgstr "インド"

msgid "Indonesia"
msgstr "インドネシア"

msgid ""Iran"
msgstr "イラン・イスラム共和国"

msgid "Iraq"
msgstr "イラク"

msgid "Ireland"
msgstr "アイルランド"

msgid "Isle of Man"
msgstr "マン島"

msgid "Israel"
msgstr "イスラエル"

msgid "Italy"
msgstr "イタリア"

msgid "Jamaica"
msgstr "ジャマイカ"

msgid "Japan"
msgstr "日本"

msgid "Jersey"
msgstr "ジャージー"

msgid "Jordan"
msgstr "ヨルダン"

msgid "Kazakhstan"
msgstr "カザフスタン"

msgid "Kenya"
msgstr "ケニア"

msgid "Kiribati"
msgstr "キリバス"

msgid ""Korea"
msgstr "朝鮮民主主義人民共和国"

msgid ""Korea"
msgstr "大韓民国"

msgid "Kuwait"
msgstr "クウェート"

msgid "Kyrgyzstan"
msgstr "キルギス"

msgid "Lao People's Democratic Republic"
msgstr "ラオス人民民主共和国"

msgid "Latvia"
msgstr "ラトビア"

msgid "Lebanon"
msgstr "レバノン"

msgid "Lesotho"
msgstr "レソト"

msgid "Liberia"
msgstr "リベリア"

msgid "Libya"
msgstr "リビア"

msgid "Liechtenstein"
msgstr "リヒテンシュタイン"

msgid "Lithuania"
msgstr "リトアニア"

msgid "Luxembourg"
msgstr "ルクセンブルク"

msgid "Macau"
msgstr "マカオ"

msgid ""Macedonia"
msgstr "マケドニア旧ユーゴスラビア共和国"

msgid "Madagascar"
msgstr "マダガスカル"

msgid "Malawi"
msgstr "マラウイ"

msgid "Malaysia"
msgstr "マレーシア"

msgid "Maldives"
msgstr "モルディブ"

msgid "Mali"
msgstr "マリ"

msgid "Malta"
msgstr "マルタ"

msgid "Marshall Islands"
msgstr "マーシャル諸島"

msgid "Martinique"
msgstr "マルティニーク"

msgid "Mauritania"
msgstr "モーリタニア"

msgid "Mauritius"
msgstr "モーリシャス"

msgid "Mayotte"
msgstr "マヨット"

msgid "Mexico"
msgstr "メキシコ"

msgid ""Micronesia"
msgstr "ミクロネシア連邦"

msgid ""Moldova"
msgstr "モルドバ共和国"

msgid "Monaco"
msgstr "モナコ"

msgid "Mongolia"
msgstr "モンゴル"

msgid "Montenegro"
msgstr "モンテネグロ"

msgid "Montserrat"
msgstr "モントセラト"

msgid "Morocco"
msgstr "モロッコ"

msgid "Mozambique"
msgstr "モザンビーク"

msgid "Myanmar"
msgstr "ミャンマー"

msgid "Namibia"
msgstr "ナミビア"

msgid "Nauru"
msgstr "ナウル"

msgid "Nepal"
msgstr "ネパール"

msgid "Netherlands"
msgstr "オランダ"

msgid "New Caledonia"
msgstr "ニューカレドニア"

msgid "New Zealand"
msgstr "ニュージーランド"

msgid "Nicaragua"
msgstr "ニカラグア"

msgid "Niger"
msgstr "ニジェール"

msgid "Nigeria"
msgstr "ナイジェリア"

msgid "Niue"
msgstr "ニウエ"

msgid "Norfolk Island"
msgstr "ノーフォーク島"

msgid "Northern Mariana Islands"
msgstr "北マリアナ諸島"

msgid "Norway"
msgstr "ノルウェー"

msgid "Oman"
msgstr "オマーン"

msgid "Pakistan"
msgstr "パキスタン"

msgid "Palau"
msgstr "パラオ"

msgid ""Palestinian Territory"
msgstr "パレスチナ"

msgid "Panama"
msgstr "パナマ"

msgid "Papua New Guinea"
msgstr "パプアニューギニア"

msgid "Paraguay"
msgstr "パラグアイ"

msgid "Peru"
msgstr "ペルー"

msgid "Philippines"
msgstr "フィリピン"

msgid "Pitcairn"
msgstr "ピトケアン"

msgid "Poland"
msgstr "ポーランド"

msgid "Portugal"
msgstr "ポルトガル"

msgid "Puerto Rico"
msgstr "プエルトリコ"

msgid "Qatar"
msgstr "カタール"

msgid "Romania"
msgstr "ルーマニア"

msgid "Russian Federation"
msgstr "ロシア連邦"

msgid "Rwanda"
msgstr "ルワンダ"

msgid "R?union"
msgstr "レユニオン"

msgid "Saint Barth?lemy"
msgstr "サン・バルテルミー"

msgid ""Saint Helena"
msgstr "セントヘレナ・アセンションおよびトリスタンダクーニャ"

msgid "Saint Kitts and Nevis"
msgstr "セントクリストファー・ネイビス"

msgid "Saint Lucia"
msgstr "セントルシア"

msgid "Saint Martin (French part)"
msgstr "サン・マルタン（フランス領）"

msgid "Saint Pierre and Miquelon"
msgstr "サンピエール島・ミクロン島"

msgid "Saint Vincent and the Grenadines"
msgstr "セントビンセントおよびグレナディーン諸島"

msgid "Samoa"
msgstr "サモア"

msgid "San Marino"
msgstr "サンマリノ"

msgid "Sao Tome and Principe"
msgstr "サントメ・プリンシペ"

msgid "Saudi Arabia"
msgstr "サウジアラビア"

msgid "Senegal"
msgstr "セネガル"

msgid "Serbia"
msgstr "セルビア"

msgid "Seychelles"
msgstr "セーシェル"

msgid "Sierra Leone"
msgstr "シエラレオネ"

msgid "Singapore"
msgstr "シンガポール"

msgid "Sint Maarten (Dutch part)"
msgstr "シント・マールテン（オランダ領）"

msgid "Slovakia"
msgstr "スロバキア"

msgid "Slovenia"
msgstr "スロベニア"

msgid "Solomon Islands"
msgstr "ソロモン諸島"

msgid "Somalia"
msgstr "ソマリア"

msgid "South Africa"
msgstr "南アフリカ"

msgid "South Georgia and the South Sandwich Islands"
msgstr "サウスジョージア・サウスサンドウィッチ諸島"

msgid "South Sudan"
msgstr "南スーダン"

msgid "Spain"
msgstr "スペイン"

msgid "Sri Lanka"
msgstr "スリランカ"

msgid "Sudan"
msgstr "スーダン"

msgid "Suriname"
msgstr "スリナム"

msgid "Svalbard and Jan Mayen"
msgstr "スヴァールバル諸島およびヤンマイエン島"

msgid "Swaziland"
msgstr "スワジランド"

msgid "Sweden"
msgstr "スウェーデン"

msgid "Switzerland"
msgstr "スイス"

msgid "Syrian Arab Republic"
msgstr "シリア・アラブ共和国"

msgid ""Taiwan"
msgstr "台湾"

msgid "Tajikistan"
msgstr "タジキスタン"

msgid ""Tanzania"
msgstr "タンザニア"

msgid "Thailand"
msgstr "タイ"

msgid "Timor-Leste"
msgstr "東ティモール"

msgid "Togo"
msgstr "トーゴ"

msgid "Tokelau"
msgstr "トケラウ"

msgid "Tonga"
msgstr "トンガ"

msgid "Trinidad and Tobago"
msgstr "トリニダード・トバゴ"

msgid "Tunisia"
msgstr "チュニジア"

msgid "Turkey"
msgstr "トルコ"

msgid "Turkmenistan"
msgstr "トルクメニスタン"

msgid "Turks and Caicos Islands"
msgstr "タークス・カイコス諸島"

msgid "Tuvalu"
msgstr "ツバル"

msgid "Uganda"
msgstr "ウガンダ"

msgid "Ukraine"
msgstr "ウクライナ"

msgid "United Arab Emirates"
msgstr "アラブ首長国連邦"

msgid "United Kingdom"
msgstr "イギリス"

msgid "United States"
msgstr "アメリカ合衆国"

msgid "United States Minor Outlying Islands"
msgstr "合衆国領有小離島"

msgid "Uruguay"
msgstr "ウルグアイ"

msgid "Uzbekistan"
msgstr "ウズベキスタン"

msgid "Vanuatu"
msgstr "バヌアツ"

msgid ""Venezuela"
msgstr "ベネズエラ・ボリバル共和国"

msgid "Viet Nam"
msgstr "ベトナム"

msgid ""Virgin Islands"
msgstr "イギリス領ヴァージン諸島"

msgid ""Virgin Islands"
msgstr "アメリカ領ヴァージン諸島"

msgid "Wallis and Futuna"
msgstr "ウォリス・フツナ"

msgid "Western Sahara"
msgstr "西サハラ"

msgid "Yemen"
msgstr "イエメン"

msgid "Zambia"
msgstr "ザンビア"

msgid "Zimbabwe"
msgstr "ジンバブエ"

msgid "Aland Islands"
msgstr "オーランド諸島"

