# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-06 09:37


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='file_path',
            field=models.FilePathField(default=None, null=True),
        ),
    ]
