# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-07 00:10


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_feed_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='file_name',
            field=models.TextField(default=None, max_length=1024, null=True),
        ),
    ]
