# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-07 07:22


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_feed_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='tlp',
            field=models.CharField(choices=[('RED', 'RED'), ('AMBER', 'AMBER'), ('GREEN', 'GREEN'), ('WHITE', 'WHITE')], default='AMBER', max_length=10),
        ),
    ]
