# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-14 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_auto_20170710_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FilePathField(default=None, null=True)),
                ('file_name', models.TextField(default=None, max_length=1024, null=True)),
            ],
            options={
                'verbose_name': 'AttachFile',
                'verbose_name_plural': 'AttachFile',
            },
        ),
        migrations.RemoveField(
            model_name='feed',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='file_path',
        ),
        migrations.AddField(
            model_name='feed',
            name='file',
            field=models.ManyToManyField(to='feeds.AttachFile'),
        ),
    ]
