# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-16 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0011_auto_20170914_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='sharing_group',
            field=models.CharField(choices=[(b'Malware', 'SHARING_GROUP_Malware'), (b'Ransomware', 'SHARING_GROUP_Ransomware'), (b'DDos', 'SHARING_GROUP_DDos'), (b'APT', 'SHARING_GROUP_APT'), (b'Vulnerability', 'SHARING_GROUP_Vulnerability'), (b'Phishing', 'SHARING_GROUP_Phishing'), (b'Web Site', 'SHARING_GROUP_Web Site'), (b'Cyber-attack Warning', 'SHARING_GROUP_Cyber-attack Warning'), (b'IoT', 'SHARING_GROUP_IoT'), (b'Security Reports', 'SHARING_GROUP_Security Reports'), (b'Tokyo Olympics/Paralympics 2020', 'SHARING_GROUP_Tokyo Olympics/Paralympics 2020'), (b'Rugby World Cup 2019', 'SHARING_GROUP_Rugby World Cup 2019'), (b'Carrier', 'SHARING_GROUP_Carrier'), (b'Financial Services', 'SHARING_GROUP_Financial Services'), (b'Defense Industries and MoD', 'SHARING_GROUP_Defense Industries and MoD'), (b'Hokkaido Region', 'SHARING_GROUP_Hokkaido Region'), (b'Tohoku Region', 'SHARING_GROUP_Tohoku Region'), (b'Kanto Region', 'SHARING_GROUP_Kanto Region'), (b'Chubu Region', 'SHARING_GROUP_Chubu Region'), (b'Kansai Region', 'SHARING_GROUP_Kansai Region'), (b'Chugoku Region', 'SHARING_GROUP_Chugoku Region'), (b'Shikoku Region', 'SHARING_GROUP_Shikoku Region'), (b'Kyushu Region', 'SHARING_GROUP_Kyushu Region')], default=b'csc', max_length=128, null=True),
        ),
    ]
