# Generated by Django 1.10.4 on 2017-10-30 07:50


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0012_auto_20171016_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='package_id',
            field=models.TextField(max_length=128, null=True),
        ),
    ]
