# Generated by Django 1.10.4 on 2017-11-10 09:21


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0013_feed_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='sharing_group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
        ),
    ]
