# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-02 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0015_auto_20180209_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='files',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='sharing_group',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='sharing_people',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='user',
        ),
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
