# Generated by Django 1.10.4 on 2018-03-02 06:26


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0016_auto_20180302_1523'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttachFile',
        ),
    ]
