# Generated by Django 1.10.4 on 2018-07-06 02:46


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0012_profile_role'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0017_delete_attachfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(max_length=1024)),
                ('file_path', models.FilePathField(default=None, max_length=1024, null=True)),
                ('package_id', models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('package_id', models.CharField(default='', max_length=128, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(null=True)),
                ('post', models.TextField(max_length=1024)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('title', models.TextField(default=None, max_length=1024, null=True)),
                ('stix_file_path', models.FilePathField(default=None, max_length=1024, null=True)),
                ('tlp', models.CharField(choices=[(b'RED', b'RED'), (b'AMBER', b'AMBER'), (b'GREEN', b'GREEN'), (b'WHITE', b'WHITE')], default='AMBER', max_length=10)),
                ('sharing_range_type', models.CharField(choices=[(b'all', b'With the CSC Community'), (b'group', b'With a group'), (b'people', b'With people')], default=b'all', max_length=10)),
                ('filename_pk', models.CharField(default='undefined', max_length=128)),
                ('screen_name', models.CharField(default='', max_length=128)),
                ('screen_affiliation', models.CharField(default='', max_length=50)),
                ('screen_instance', models.CharField(default='', max_length=128, null=True)),
                ('is_valid_user', models.BooleanField(default='True')),
                ('region_code', models.CharField(default='', max_length=128)),
                ('ci', models.CharField(default='', max_length=128)),
                ('files', models.ManyToManyField(to='feeds.AttachFile')),
                ('sharing_group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
                ('sharing_people', models.ManyToManyField(related_name='feed_sharing_people', to='authentication.Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
                'verbose_name': 'Feed',
                'verbose_name_plural': 'Feeds',
            },
        ),
    ]
