# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-01 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('subdivision_name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=16)),
            ],
        ),
    ]
