# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-01 10:05


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='subdivision_name',
            new_name='administrative_area',
        ),
    ]
