# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-01 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170801_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('alpha_2', models.CharField(max_length=2)),
                ('alpha_3', models.CharField(max_length=3)),
                ('country_code', models.IntegerField()),
                ('iso_3166_2', models.CharField(max_length=16)),
                ('region', models.CharField(max_length=16)),
                ('sub_region', models.CharField(max_length=32)),
                ('region_code', models.IntegerField()),
                ('sub_region_code', models.IntegerField()),
            ],
        ),
    ]
