# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-02-12 08:15


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0022_auto_20190212_0215'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
