# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-13 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='affiliation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
