# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-24 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20170714_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tlp',
            field=models.CharField(choices=[(b'RED', b'RED'), (b'AMBER', b'AMBER'), (b'GREEN', b'GREEN'), (b'WHITE', b'WHITE')], default='AMBER', max_length=10),
        ),
    ]
