# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-01 06:09


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('authentication', '0006_profile_tlp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Region'),
        ),
    ]
