# Generated by Django 1.10.4 on 2017-08-02 04:22


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_profile_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Region'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sector',
            field=models.CharField(choices=[(b'chemical', b'Chemical Sector'), (b'commercial', b'Commercial Facilities Sector'), (b'communication', b'Communications Sector'), (b'critical', b'Critical Manufacturing Sector'), (b'dams', b'Dams Sector'), (b'defense', b'Defense Industrial Base Sector'), (b'emergency', b'Emergency Services Sector'), (b'energy', b'Energy Sector'), (b'financial', b'Financial Services Sector'), (b'food', b'Food and Agriculture Sector'), (b'government', b'Government Facilities Sector'), (b'healthcare', b'Healthcare and Public Health Sector'), (b'information', b'Information Technology Sector'), (b'nuclear', b'Nuclear Reactors, Materials, and Waste Sector'), (b'other', b'Other'), (b'transport', b'Transportation Systems Sector'), (b'water', b'Water and Wastewater Systems Sector')], max_length=128, null=True),
        ),
    ]
