# Generated by Django 1.10.4 on 2017-08-10 06:23


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20170802_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[(b'en', b'English'), (b'pt-br', b'Portuguese'), (b'es', b'Spanish'), (b'ja', b'Japanese'), (b'zh_CN', b'Chinese')], default='en', max_length=4),
        ),
    ]
