# Generated by Django 1.10.4 on 2018-08-15 07:09


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20180807_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='scan_txt',
            field=models.BooleanField(default=True),
        ),
    ]
