# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-08-16 04:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_profile_scan_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='threat_actors',
            field=models.TextField(default='', max_length=10240),
        ),
    ]
