# Generated by Django 1.10.4 on 2018-08-16 07:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_profile_threat_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='indicator_white_list',
            field=models.TextField(default='', max_length=10240),
        ),
    ]
