import threading
from django.apps import AppConfig
from django.core.management import call_command
from django.utils.translation import ugettext_lazy
from stip.common.boot import is_skip_sequence
from django.conf import settings as django_settings
# from daemon.email.smtp import start_mail_thread


class StipSnsBoot(AppConfig):
    name = 'boot_sns'

    def ready(self):
        from ctirs.models import Region, Country, SNSConfig
        from feeds.mongo import init_attck_collection

        is_skip_sequnece = is_skip_sequence()
        if not is_skip_sequnece:
            print('>>> Start Auto Deploy')
            print('>>> Start collcect static --noinput')
            # collectstatic
            call_command('collectstatic', '--noinput')

            # loaddata (region)
            region_count = Region.objects.count()
            print('>>> region record count: ' + str(region_count))
            if region_count == 0:
                print('>>> Start loaddata region')
                call_command('loaddata', 'region')
                print('>>> region record count: ' + str(Region.objects.count()))
            else:
                print('>>> Skip loaddata region')

            # loaddata (country)
            country_count = Country.objects.count()
            print('>>> coutnry record count: ' + str(country_count))
            if country_count == 0:
                print('>>> Start loaddata country')
                call_command('loaddata', 'country')
                print('>>> coutnry record count: ' + str(Country.objects.count()))
            else:
                print('>>> Skip loaddata country')

            # loaddata (sns_config)
            sns_config_count = SNSConfig.objects.count()
            print('>>> sns_config record count: ' + str(sns_config_count))
            if sns_config_count == 0:
                print('>>> Start loaddata sns_config')
                call_command('loaddata', 'sns_config')
                print('>>> sns_config record count: ' + str(SNSConfig.objects.count()))
            else:
                print('>>> Skip loaddata sns_config')

        # ATTCK コレクションがない場合は起動時に取得し、攻撃者情報リストを取得する
        init_attck_collection()

        # smtp daemon 起動
        # start_mail_thread()

        # country/region の日本語対応
        self.convert_country_and_region_in_japanese()

        # slack WebSocket start
        from daemon.slack.receive import start_receive_slack_thread
        start_receive_slack_thread()

    def convert_country_and_region_in_japanese(self):
        # 日本語化対象
        # 日本の都道府県
        ugettext_lazy('Aichi')
        ugettext_lazy('Akita')
        ugettext_lazy('Aomori')
        ugettext_lazy('Chiba')
        ugettext_lazy('Ehime')
        ugettext_lazy('Fukui')
        ugettext_lazy('Fukuoka')
        ugettext_lazy('Fukushima')
        ugettext_lazy('Gifu')
        ugettext_lazy('Gunma')
        ugettext_lazy('Hiroshima')
        ugettext_lazy('Hokkaido')
        ugettext_lazy('Hyogo')
        ugettext_lazy('Ibaraki')
        ugettext_lazy('Ishikawa')
        ugettext_lazy('Iwate')
        ugettext_lazy('Kagawa')
        ugettext_lazy('Kagoshima')
        ugettext_lazy('Kanagawa')
        ugettext_lazy('Kochi')
        ugettext_lazy('Kumamoto')
        ugettext_lazy('Kyoto')
        ugettext_lazy('Mie')
        ugettext_lazy('Miyagi')
        ugettext_lazy('Miyazaki')
        ugettext_lazy('Nagano')
        ugettext_lazy('Nagasaki')
        ugettext_lazy('Nara')
        ugettext_lazy('Niigata')
        ugettext_lazy('Oita')
        ugettext_lazy('Okayama')
        ugettext_lazy('Okinawa')
        ugettext_lazy('Osaka')
        ugettext_lazy('Saga')
        ugettext_lazy('Saitama')
        ugettext_lazy('Shiga')
        ugettext_lazy('Shimane')
        ugettext_lazy('Shizuoka')
        ugettext_lazy('Tochigi')
        ugettext_lazy('Tokushima')
        ugettext_lazy('Tokyo')
        ugettext_lazy('Tottori')
        ugettext_lazy('Toyama')
        ugettext_lazy('Wakayama')
        ugettext_lazy('Yamagata')
        ugettext_lazy('Yamaguchi')
        ugettext_lazy('Yamanashi')

        # 国名
        ugettext_lazy('Afghanistan')
        ugettext_lazy('Åland Islands')
        ugettext_lazy('Albania')
        ugettext_lazy('Algeria')
        ugettext_lazy('American Samoa')
        ugettext_lazy('Andorra')
        ugettext_lazy('Angola')
        ugettext_lazy('Anguilla')
        ugettext_lazy('Antarctica')
        ugettext_lazy('Antigua and Barbuda')
        ugettext_lazy('Argentina')
        ugettext_lazy('Armenia')
        ugettext_lazy('Aruba')
        ugettext_lazy('Australia')
        ugettext_lazy('Austria')
        ugettext_lazy('Azerbaijan')
        ugettext_lazy('Bahamas')
        ugettext_lazy('Bahrain')
        ugettext_lazy('Bangladesh')
        ugettext_lazy('Barbados')
        ugettext_lazy('Belarus')
        ugettext_lazy('Belgium')
        ugettext_lazy('Belize')
        ugettext_lazy('Benin')
        ugettext_lazy('Bermuda')
        ugettext_lazy('Bhutan')
        ugettext_lazy('Bolivia (Plurinational State of)')
        ugettext_lazy('Bonaire, Sint Eustatius and Saba')
        ugettext_lazy('Bosnia and Herzegovina')
        ugettext_lazy('Botswana')
        ugettext_lazy('Bouvet Island')
        ugettext_lazy('Brazil')
        ugettext_lazy('British Indian Ocean Territory')
        ugettext_lazy('Brunei Darussalam')
        ugettext_lazy('Bulgaria')
        ugettext_lazy('Burkina Faso')
        ugettext_lazy('Burundi')
        ugettext_lazy('Cambodia')
        ugettext_lazy('Cameroon')
        ugettext_lazy('Canada')
        ugettext_lazy('Cabo Verde')
        ugettext_lazy('Cayman Islands')
        ugettext_lazy('Central African Republic')
        ugettext_lazy('Chad')
        ugettext_lazy('Chile')
        ugettext_lazy('China')
        ugettext_lazy('Christmas Island')
        ugettext_lazy('Cocos (Keeling) Islands')
        ugettext_lazy('Colombia')
        ugettext_lazy('Comoros')
        ugettext_lazy('Congo')
        ugettext_lazy('Congo (Democratic Republic of the)')
        ugettext_lazy('Cook Islands')
        ugettext_lazy('Costa Rica')
        ugettext_lazy('Côte d\'Ivoire')
        ugettext_lazy('Croatia')
        ugettext_lazy('Cuba')
        ugettext_lazy('Curaçao')
        ugettext_lazy('Cyprus')
        ugettext_lazy('Czech Republic')
        ugettext_lazy('Denmark')
        ugettext_lazy('Djibouti')
        ugettext_lazy('Dominica')
        ugettext_lazy('Dominican Republic')
        ugettext_lazy('Ecuador')
        ugettext_lazy('Egypt')
        ugettext_lazy('El Salvador')
        ugettext_lazy('Equatorial Guinea')
        ugettext_lazy('Eritrea')
        ugettext_lazy('Estonia')
        ugettext_lazy('Ethiopia')
        ugettext_lazy('Falkland Islands (Malvinas)')
        ugettext_lazy('Faroe Islands')
        ugettext_lazy('Fiji')
        ugettext_lazy('Finland')
        ugettext_lazy('France')
        ugettext_lazy('French Guiana')
        ugettext_lazy('French Polynesia')
        ugettext_lazy('French Southern Territories')
        ugettext_lazy('Gabon')
        ugettext_lazy('Gambia')
        ugettext_lazy('Georgia')
        ugettext_lazy('Germany')
        ugettext_lazy('Ghana')
        ugettext_lazy('Gibraltar')
        ugettext_lazy('Greece')
        ugettext_lazy('Greenland')
        ugettext_lazy('Grenada')
        ugettext_lazy('Guadeloupe')
        ugettext_lazy('Guam')
        ugettext_lazy('Guatemala')
        ugettext_lazy('Guernsey')
        ugettext_lazy('Guinea')
        ugettext_lazy('Guinea-Bissau')
        ugettext_lazy('Guyana')
        ugettext_lazy('Haiti')
        ugettext_lazy('Heard Island and McDonald Islands')
        ugettext_lazy('Holy See')
        ugettext_lazy('Honduras')
        ugettext_lazy('Hong Kong')
        ugettext_lazy('Hungary')
        ugettext_lazy('Iceland')
        ugettext_lazy('India')
        ugettext_lazy('Indonesia')
        ugettext_lazy('Iran (Islamic Republic of)')
        ugettext_lazy('Iraq')
        ugettext_lazy('Ireland')
        ugettext_lazy('Isle of Man')
        ugettext_lazy('Israel')
        ugettext_lazy('Italy')
        ugettext_lazy('Jamaica')
        ugettext_lazy('Japan')
        ugettext_lazy('Jersey')
        ugettext_lazy('Jordan')
        ugettext_lazy('Kazakhstan')
        ugettext_lazy('Kenya')
        ugettext_lazy('Kiribati')
        ugettext_lazy('Korea (Democratic People\'s Republic of)')
        ugettext_lazy('Korea (Republic of)')
        ugettext_lazy('Kuwait')
        ugettext_lazy('Kyrgyzstan')
        ugettext_lazy('Lao People\'s Democratic Republic')
        ugettext_lazy('Latvia')
        ugettext_lazy('Lebanon')
        ugettext_lazy('Lesotho')
        ugettext_lazy('Liberia')
        ugettext_lazy('Libya')
        ugettext_lazy('Liechtenstein')
        ugettext_lazy('Lithuania')
        ugettext_lazy('Luxembourg')
        ugettext_lazy('Macao')
        ugettext_lazy('Macedonia (the former Yugoslav Republic of)')
        ugettext_lazy('Madagascar')
        ugettext_lazy('Malawi')
        ugettext_lazy('Malaysia')
        ugettext_lazy('Maldives')
        ugettext_lazy('Mali')
        ugettext_lazy('Malta')
        ugettext_lazy('Marshall Islands')
        ugettext_lazy('Martinique')
        ugettext_lazy('Mauritania')
        ugettext_lazy('Mauritius')
        ugettext_lazy('Mayotte')
        ugettext_lazy('Mexico')
        ugettext_lazy('Micronesia (Federated States of)')
        ugettext_lazy('Moldova (Republic of)')
        ugettext_lazy('Monaco')
        ugettext_lazy('Mongolia')
        ugettext_lazy('Montenegro')
        ugettext_lazy('Montserrat')
        ugettext_lazy('Morocco')
        ugettext_lazy('Mozambique')
        ugettext_lazy('Myanmar')
        ugettext_lazy('Namibia')
        ugettext_lazy('Nauru')
        ugettext_lazy('Nepal')
        ugettext_lazy('Netherlands')
        ugettext_lazy('New Caledonia')
        ugettext_lazy('New Zealand')
        ugettext_lazy('Nicaragua')
        ugettext_lazy('Niger')
        ugettext_lazy('Nigeria')
        ugettext_lazy('Niue')
        ugettext_lazy('Norfolk Island')
        ugettext_lazy('Northern Mariana Islands')
        ugettext_lazy('Norway')
        ugettext_lazy('Oman')
        ugettext_lazy('Pakistan')
        ugettext_lazy('Palau')
        ugettext_lazy('Palestine, State of')
        ugettext_lazy('Panama')
        ugettext_lazy('Papua New Guinea')
        ugettext_lazy('Paraguay')
        ugettext_lazy('Peru')
        ugettext_lazy('Philippines')
        ugettext_lazy('Pitcairn')
        ugettext_lazy('Poland')
        ugettext_lazy('Portugal')
        ugettext_lazy('Puerto Rico')
        ugettext_lazy('Qatar')
        ugettext_lazy('Réunion')
        ugettext_lazy('Romania')
        ugettext_lazy('Russian Federation')
        ugettext_lazy('Rwanda')
        ugettext_lazy('Saint Barthélemy')
        ugettext_lazy('Saint Helena, Ascension and Tristan da Cunha')
        ugettext_lazy('Saint Kitts and Nevis')
        ugettext_lazy('Saint Lucia')
        ugettext_lazy('Saint Martin (French part)')
        ugettext_lazy('Saint Pierre and Miquelon')
        ugettext_lazy('Saint Vincent and the Grenadines')
        ugettext_lazy('Samoa')
        ugettext_lazy('San Marino')
        ugettext_lazy('Sao Tome and Principe')
        ugettext_lazy('Saudi Arabia')
        ugettext_lazy('Senegal')
        ugettext_lazy('Serbia')
        ugettext_lazy('Seychelles')
        ugettext_lazy('Sierra Leone')
        ugettext_lazy('Singapore')
        ugettext_lazy('Sint Maarten (Dutch part)')
        ugettext_lazy('Slovakia')
        ugettext_lazy('Slovenia')
        ugettext_lazy('Solomon Islands')
        ugettext_lazy('Somalia')
        ugettext_lazy('South Africa')
        ugettext_lazy('South Georgia and the South Sandwich Islands')
        ugettext_lazy('South Sudan')
        ugettext_lazy('Spain')
        ugettext_lazy('Sri Lanka')
        ugettext_lazy('Sudan')
        ugettext_lazy('Suriname')
        ugettext_lazy('Svalbard and Jan Mayen')
        ugettext_lazy('Swaziland')
        ugettext_lazy('Sweden')
        ugettext_lazy('Switzerland')
        ugettext_lazy('Syrian Arab Republic')
        ugettext_lazy('Taiwan, Province of China')
        ugettext_lazy('Tajikistan')
        ugettext_lazy('Tanzania, United Republic of')
        ugettext_lazy('Thailand')
        ugettext_lazy('Timor-Leste')
        ugettext_lazy('Togo')
        ugettext_lazy('Tokelau')
        ugettext_lazy('Tonga')
        ugettext_lazy('Trinidad and Tobago')
        ugettext_lazy('Tunisia')
        ugettext_lazy('Turkey')
        ugettext_lazy('Turkmenistan')
        ugettext_lazy('Turks and Caicos Islands')
        ugettext_lazy('Tuvalu')
        ugettext_lazy('Uganda')
        ugettext_lazy('Ukraine')
        ugettext_lazy('United Arab Emirates')
        ugettext_lazy('United Kingdom of Great Britain and Northern Ireland')
        ugettext_lazy('United States of America')
        ugettext_lazy('United States Minor Outlying Islands')
        ugettext_lazy('Uruguay')
        ugettext_lazy('Uzbekistan')
        ugettext_lazy('Vanuatu')
        ugettext_lazy('Venezuela (Bolivarian Republic of)')
        ugettext_lazy('Viet Nam')
        ugettext_lazy('Virgin Islands (British)')
        ugettext_lazy('Virgin Islands (U.S.)')
        ugettext_lazy('Wallis and Futuna')
        ugettext_lazy('Western Sahara')
        ugettext_lazy('Yemen')
        ugettext_lazy('Zambia')
        ugettext_lazy('Zimbabwe')
